#!/bin/bash

docker run \
    -ti \
    --rm \
    -d --device /dev/dri \
    -v /tmp/.X11-unix:/tmp/.X11-unix  \
    -v $HOME:/home/vfac \
    -v $PWD:/app/ \
    --env DISPLAY=unix$DISPLAY  \
    --name vscode  \
    --net="host"  \
    --user $(id -u $(whoami)):$(id -g $(whoami)) \
    vscode
